version: 0.2
sparkVersion: 3.1.1
image: docker.io/hrmguilherme/lixar-events-sensor:5.0.0
jar: local:///opt/spark/work-dir/lixar-events-processor.jar
mainClass: com.lixar.events.StreamingSensor
fileDependencies: [ local:///opt/spark/work-dir/bigquery.json,local:///opt/spark/jars/spark-bigquery-with-dependencies_2.12-0.25.2.jar,local:///opt/spark/jars/spark-redis_2.12-3.1.0-SNAPSHOT-jar-with-dependencies.jar]
environment: kind
serviceAccount: spark
volumes:
  - name: config-vol
    configMap:
      name: dummy-cm
driver:
  cores: 2
  memory: "2096m"
  labels:
    version: 3.1.1
executor:
  cores: 2
  instances: 1
  memory: "2096m"
  labels:
    version: 3.1.1
hadoopConf:
  "google.cloud.auth.service.account.enable": true
  "spark.redis.host": 10.107.30.251
sparkConf:
  "spark.hadoop.fs.AbstractFileSystem.gs.impl": com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS
  "fs.gs.project.id": spark
  "fs.gs.system.bucket": spark
  "spark.redis.host": 10.107.30.251
hostNetwork: false
imagePullPolicy: Always
userId: 0